### ISSUE TITLE
newTeamController

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#107]
Implement newTeamController to grab POST data sent in to save a Team. It would get Team attributes (name) and userIDs with users assigned to this team, call database utilitiy methods to save them to the DB and output a message, either successful or failed.

Ideally allow adding multiple users to the team before submitting the form.

**Comment by ThoraX-SVK** [comment]
What kind of manipulation do we want? Add user, delete user, from team? @timbez

**Comment by timbez** [comment]
I guess so
