### ISSUE TITLE
deleteTeamFromDB

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#117]
Implement a database utility method to remove Team from DB specified by teamID.

i.e. 

function deleteTeamFromDB($teamID) {
//do removing
}

**Comment by ThoraX-SVK** [comment]
Shoudl it also remove all routes assiged to it? All runs assiged to that team route?

**Comment by ThoraX-SVK** [comment]
Problem is, we can not delete team from DB, because of other tables referencing that row.

**Comment by ThoraX-SVK** [comment]
Do we really need this? @timbez

**Comment by timbez** [comment]
is it in the requiremets? if not then forget about it
