### ISSUE TITLE
Add new route link position wrong when no route selected

### ISSUE THREAD

**Issue by ThoraX-SVK** [ThoraX-SVK/Webte2#124]
When all routes are hidden, this happens 
![csswrong](https://user-images.githubusercontent.com/30527564/40138637-8a2d4d74-594d-11e8-885a-c6d48627a0fd.png)

**Comment by Liblink** [comment]
When i noticed this issue, i wasnt able to replicate the behaviour shown in the picture. Maybe the issue has been solved in the meantime. Could you confirm, that this issue has been fixed?

**Comment by ThoraX-SVK** [comment]
Fixed
