### ISSUE TITLE
Make link to home page from title page

### ISSUE THREAD

**Issue by ThoraX-SVK** [ThoraX-SVK/Webte2#125]
When user is logged in and he gets to title page, either close his session OR make a link so he can return without typing address of home page.

Right now he has to either type something to address bar or login again

**Comment by Liblink** [comment]
Maybe if user is already logged in, loginPage.php should redirect him to homePage automatically?

**Comment by ThoraX-SVK** [comment]
@timbez Could you take this?

**Comment by timbez** [comment]
sure
