### ISSUE TITLE
What should be in INFO part of single route detail?

### ISSUE THREAD

**Issue by ThoraX-SVK** [ThoraX-SVK/Webte2#131]
What interresting should we put to single route detail? Distance, name, remaining, biggest contributor, biggest contribution? Any ideas?

**Comment by ThoraX-SVK** [comment]
Wild ideas, with huge SQL selects are particularly welcome!

**Comment by Liblink** [comment]
name
distance
type (private/public/team)
number of contributors (how many people has it as active)
how many KM have been added today?

**Comment by ThoraX-SVK** [comment]
I left out km added today, might come back to it later, depending on our time schedule.

Now full description gives us this data:
    return array(
        'name' => ''Route name'
        'totalDistance' => 'Total Route Distance',
        'activeContributorsCount' => 'How many users have this route as their active',
        'routeMode' => 'Route mode'
    );
