### ISSUE TITLE
user stats page table + average speed and distance calculation

### ISSUE THREAD

**Issue by Liblink** [ThoraX-SVK/Webte2#152]
"Každý užívateľ si v rámci aplikácie bude mocť pozrieť podrobnú tabuľku svojich výkonov, t.j.
v ktorý deň koľko odbehol/odjazdil, atď (všetky údaje z formulára z bodu B).Posledným stĺpcom tabuľky bude priemerná rýchlosť na tréningu."

So there should be this type of table:
> "All your runs"
-->date
-->time of start
-->time of end
-->rating
-->distance
-->average speed

Pod tabuľkou sa zobrazí priemerná hodnota odbehnutých/odjazdených kilometrov na jeden
tréning
->average distance for one run

**Comment by ThoraX-SVK** [comment]
This
"All your runs"
-->date
-->time of start
-->time of end
-->rating
-->distance
-->average speed

If I understand it correctly, every row should have this data? What about route to which that run is contributing?

**Comment by Liblink** [comment]
yes, every row should have this data.
and route to which is run contributing is a good idea.
