### ISSUE TITLE
All routes page

### ISSUE THREAD

**Issue by ThoraX-SVK** [ThoraX-SVK/Webte2#42]
This page should request route service to show tables, _related info_ #40

There should be three tick marks somewhere, to enable filtering. There are two ways how to do this. We can either on every change call AJAX **or** have a button that will refresh table on click.
![tickmarks](https://user-images.githubusercontent.com/30527564/39957842-e93654ac-55f9-11e8-8526-627e29e3df00.png)

**Comment by Liblink** [comment]
Didnt we agree, that on the home page will user see his active route and will be able to add new kilometers to this active route?
This to me seems like page "tables", not "home".
And i dont see any issue related to "home" page containing active run and with ability to add new kilometers. So there should be probably added new issue related to "home" page, with the drawning of the layout we agreed on in school.
@ThoraX-SVK

**Comment by ThoraX-SVK** [comment]
Yes, mistake on my side, name of this issue is wrong, will assign you the right one and rename this.
