### ISSUE TITLE
get all routes with given mode

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#92]
To implement a function that fetches information on all routes with given mode (private, public ...)

the function takes mode as a parameter. Mode is one of the 3 options /constants/ defined in routeConstants.php

-- duplicate of #40
#omylem

**Comment by ThoraX-SVK** [comment]
Should it take into account user visibility?

**Comment by Liblink** [comment]
Yes, it should

**Comment by Liblink** [comment]
Isnt this the same issue #41 ?

**Comment by ThoraX-SVK** [comment]
Is this enough info? 

array(
            'distanceData' => array(
                'totalDistance' => 300,
                'done' => 120,
                'remaining' => 180),
            'name' => 'route1',
            'isActiveForUser' => true
)

**Comment by ThoraX-SVK** [comment]
@Liblink yes, that service should be called from site template and it should print table. Maybe should be controller...

**Comment by ThoraX-SVK** [comment]
Done
