### ISSUE TITLE
get team information based on teamID

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#97]
Implement a database util method to fetch data on team based on given teamID.

The data could be respresented as:
array (
    "teamName" => "team 1",
    "teamMembers" => array (
                                            array ( "userID" => 1, maybe more info),
                                            array ( "userID" => 2, maybe more info),)
);

or simplified if there is no more info on users excecpt for their userIDs

**Comment by ThoraX-SVK** [comment]
Team does not have activeRouteID. Only user can have in DB field activeRoute_fk.

**Comment by ThoraX-SVK** [comment]
Yes, there will be table TeamRoutes with team_fk and route_fk
