### ISSUE TITLE
get all users registered in system 

### ISSUE THREAD

**Issue by timbez** [ThoraX-SVK/Webte2#98]
Implement a database util to get all users from database. Could take an optional parameter that decides whether to get all users or just users that have been activated.

Example:
return array (
    array ("userID" => 1, "email" => a@a.b, etc...),
    array ("userID" => 2, "email" => a@b.c, etc...),
)

**Comment by ThoraX-SVK** [comment]
Can we please specify, what do we want to get from DB? All data for user? As in function createEmptyUser() or just some specific parts?

**Comment by timbez** [comment]
I need this utility basically just to create a service that outputs a HTML select with all available users, so the admin can choose from them and assign them to teams. Therefore i do not need all the data. I am not sure if the method will be used for anything else, where all the user data will be required. For now I think we can just assume that userID, email, name, surname will suffice

**Comment by ThoraX-SVK** [comment]
Will do.

**Comment by timbez** [comment]
can you also provide "is activated" attribute? thanks @ThoraX-SVK

**Comment by ThoraX-SVK** [comment]
resolved in #108
